### ISSUE TITLE
Problem with org-mode archive when on a task

### ISSUE THREAD

**Issue by macdrifter** [aziz/PlainTasks#224] opened 2015-03-06 14:42 UTC
I've noticed that when org-mode archive is triggered when the cursor is on a subtask of a project, everything below that task (including all projects at higher levels) is archived. This happens on both Windows and Mac.

The use case I was testing was archiving individual tasks to an archive file instead of the footer.

**Comment by vovkkk** [comment] 2015-03-06 19:52
I cannot reproduce.
Important thing to know is that this feature determine block in the same way as ST folding feature, i.e. indents *must* be consistent, so if you use literal tabs for indenting then you won’t face issue at all, whitespaces may cause problems and perhaps it should be fixed, but on the other side folding feature has the same flaw, so why bother?

**Comment by macdrifter** [comment] 2015-03-06 21:23
Here's some example data that does it consistently for me. Setup a new file with this structure. Place the cursor on at the end of "Task 2" and then use org-mode archive. Note that I am using tabs, not spaces. Triggering org-mode archive seems to archive everything between "Task 2" and "Home"

```


Work:
	- Task 1
	- Task 2
	- Task 3

	Project 2:
		- Task A
		- Task B
		- Task C

Home:

	Project 3:
		- Task 1A
```

**Comment by macdrifter** [comment] 2015-03-06 21:41
Perhaps I've misunderstood org-mode archive and this behavior is intended. Although would consider Project 2 to be a child of Task 2. Project 2 is a child of work.

**Closed** 2015-03-07 00:03 UTC
Labels: bug

**Comment by vovkkk** [comment] 2015-03-07 00:05
Though archiving a single task into sep file is not supported currently, see #218
