### ISSUE TITLE
Enhancement: Better nesting support

### ISSUE THREAD

**Issue by bfelder** [aziz/PlainTasks#355] opened 2017-08-02 17:37 UTC
Hierarchy is vital to provide structure not only to code but also to the organization of tasks. Therefore PlainTaks should feature a better support of nested structures.

In this regard, I got two related enhancement proposals.

**1. Auto indent on Enter**
Thereby the right indentation level of a respective child task is automatically selected. (Think python here.)
```
☐ Parent:|  <-- has colon = is parent, | = caret

```
On enter, the caret is positioned...
```
☐ Parent:
.... |  
```
 where Child 1 should begin
```
☐ Parent:
.... ☐ Child 1 |  
```

**2. Couple parent child tasks**

If Parent is marked complete/canceled, all children are marked complete/canceled as well.
```
✔ Parent:
    ☐ Child 1
    ☐ Child 2
```
leads to:
```
✔ Parent:
    ✔ Child 1
    ✔ Child 2
```

And vice versa if all children tasks are complete/canceled the parent task is set to complete/canceled automatically.

```
✔ Parent:
    ☐ Child 1
    ☐ Child 2
```
leads to:

```
✔ Parent:
    ✔ Child 1
    ✔ Child 2
```

**Comment by vovkkk** [comment] 2017-08-03 06:39
Earlier we had keybinding which add indent on <kbd>enter</kbd> after each task (because even if it won’t have child then it may have a note), the binding was removed in #214 
You can add removed binding in your user keybindings file and also may change `"preceding_text"` regex so it wil work only if task ends with colon.

The second proposal is a duplicate of #39

**Closed by vovkkk** 2017-08-03 06:39 UTC
