### ISSUE TITLE
Phantoms are wonky

### ISSUE THREAD

**Issue by FichteFoll** [aziz/PlainTasks#312] opened 2016-12-08 09:41 UTC
I randomly discovered that this package now makes use of phantoms (cool!), but they behave rather oddly.

1. ~~Two "Remain" lines for each `@due`.~~ fixed by updating to latest version
2. Should probably read "x remaining" instead (and "x overdue").
2. The completion preview that is shown inline should be shown *after* the closing paren. Currently the margin around phantoms is disturbing. Even moreso when an item is overdue or due today.
3. Occasionally, I don't see phantoms at all. Also, occasionally I see a phantom after a line has been removed (#307). Very inconsistent and hard to reproduce.
4. Always shows remaining seconds as `59`.
5. Phantoms update inconsistently (seemingly `on_activated`, but a one-minute interval would be ideal). Not even when changing the due date.

![sample screenshot](https://a.desu.sh/kujqkl.png)

![more sample](https://a.desu.sh/vjokxd.png)

PS: Have you considered using tagged releases (and thus being able to show update messages)?

**Comment by vovkkk** [comment] 2016-12-08 13:36
> ~~Two "Remain" lines for each `@due`.~~ fixed by updating to latest version

It means there were two instances of EventListener, may happen for example if you saved script without restart.

> 2  "x remaining" 

It is not grammatically correct, ‘remain sth’ is correct, but  the point here is to make it easier to visually parse this information, first you see what it is and then how many, ofc by default overdue tag is red and easily noticeable, but colours are customisable.

> 3 The completion preview that is shown inline should be shown after the closing paren

I’ve tried it initially too (and other options), and it seems having it within parentheses is less confusing because it is clear that it has relation to cursor, if it would be outside it may be not so clear or we would need to add hint such as ‘if you press tab now you will get this date’ or something

> 3 when an item is overdue or due today

Can we make phantom transparent? I don’t know.

> 4 Occasionally, I don't see phantoms at all.

We have two kinds of phantoms:
1. Preview due date, it is visible only for single cursor and only if cursor is within parentheses of `@due()` at pending task, and if actually typed date differs from expanded, i.e. you are not supposed to see `@due(16-12-08 11:11 16-12-08 11:11 )` (although there is regression, fixed now https://github.com/aziz/PlainTasks/commit/ff23c0a2133b400355a3c46fa0ead68012d1fa4a)
2. Remain/overdue; this are being updated (as well as highlighting of due tags) on save, load, activated, only

> 5 Always shows remaining seconds as 59

https://github.com/aziz/PlainTasks/commit/ff23c0a2133b400355a3c46fa0ead68012d1fa4a

> 6 one-minute interval would be ideal

How would you do it? while-loop? sublime.timeout or something?

> Have you considered using tagged releases (and thus being able to show update messages)?

I had to do it in FileBrowser and experience is unpleasant: it would be better if PC shows version/tag so I don’t need to add it to message, and take note from matching filename in message folder instead of message.json.
Besides, this package probably won’t introduce breaking changes so showing message is not that important, and there is rss for those who care about new features https://github.com/aziz/PlainTasks/commits/master.atom

**Comment by net** [comment] 2016-12-11 19:53
I can confirm that phantom previews are very unreliable, sometimes never appearing at all.

**Comment by vovkkk** [comment] 2016-12-11 21:10
> sometimes never appearing at all

Any details? Are you on Windows? Did you type a number greater than 99 like `@due(111)`? how looks your date_format? do you see errors in console View in main menu → Show Console?

**Comment by net** [comment] 2016-12-11 21:24
macOS Sierra, date format/tab complete working properly, no errors, installed via Package Control.

**Comment by vovkkk** [comment] 2016-12-11 21:34
Do you use any plugin that show icons in gutter? like git or brackets, that kind?

**Comment by vovkkk** [comment] 2016-12-11 21:37
Actually could you just post list of all plugins you have Preferences→Settings→Package Control→User Settings

**Comment by net** [comment] 2016-12-11 21:41
```
		"Align Arguments",
		"AlignTab",
		"ayu",
		"Base16 Color Schemes",
		"Dockerfile Syntax Highlighting",
		"Elixir",
		"ElixirSublime",
		"Elm Language Support",
		"Fix Mac Path",
		"Git",
		"GitGutter-Edge",
		"Package Control",
		"PlainTasks",
		"QuickThemes",
		"Rust Enhanced",
		"Sass",
		"Theme - Spacegray",
		"Vintageous"
```

I disabled GitGutter and the issue persists. I should mention that the live inline preview when setting a due date displays fine. It's the "remain" preview underneath the due tag which is irregular and often not displaying.

I do not have it disabled in my settings:

```
{
  "color_scheme": "Packages/User/tasks-ayu.hidden-tmTheme",
  "icon_past_due": "dot",
  "highlight_past_due": false,
  "date_format": "(%m.%d %H:%M)"
}
```
I was having issues before I added any user settings.

**Comment by vovkkk** [comment] 2016-12-11 22:00
Man... remain is not a preview, I do insist, that we use the word ‘preview’ only for the inline phantom within parentheses of `@due()`;
as said in second message of this thread, remain/overdue phantoms are updated only on save, load, activated, events of a tab/view.
This is just how it works for now, it is reliable in that sense; although sometimes it may fail because `sublime` is None which is very strange, probably bug in ST ( @FichteFoll did you ever saw it? sublime is None)

But even if it failed it will be updated on next save or load or activated event.
Also you may execute `plain_tasks_toggle_highlight_past_due` command by hand (bind to some keys or add to context menu), it should update remain/overdue stuff.

Ofc. it would be nice if it was real-time, but I concern performance and inevitable increase of complexity.
No promises, but I hope we’ll be there at some point.

**Comment by net** [comment] 2016-12-11 22:05
Oops! I guess I should've read your first reply more carefully! Apologies for wasting your time.

**Comment by FichteFoll** [comment] 2016-12-12 03:00
>( @FichteFoll did you ever saw it? sublime is None)

No, I have never seen that `sublime` is every `None` (unless it was specifically overridden, which makes no sense). Are you thinking of a function call returning `None` in case the API hasn't been initialized yet?

**Comment by FichteFoll** [comment] 2016-12-12 14:37
So, anyway, I encountered this today:

https://a.desu.sh/tynbem.mp4

Quite ... intersting I'd say.

---

>It means there were two instances of EventListener, may happen for example if you saved script without restart.

EventListeners should be removed from the event list when plugins are unloaded. However, it doesn't happen anymore, so maybe it was fixed after all or just a weird bug.

> It is not grammatically correct, ‘remain sth’ is correct

So, English is not my first language, but "to remain" usually operates on adjectives (i.e. to remain calm). 
The "remaining" that is used in "2h remaining" is also an adjective, just like"overdue", and gives meaning to the time span.

> I’ve tried it initially too (and other options), and it seems having it within parentheses is less confusing because it is clear that it has relation to cursor, if it would be outside it may be not so clear or we would need to add hint such as ‘if you press tab now you will get this date’ or something

Well, it doesn't say "press tab" currently either, and I highly doubt that displaying it before or after the paren makes a difference in that regard. It does make a difference for visuals however and moving the closing paren that far away messes way more with me than showing a phantom preview behind it. Not to mention outlines or background colors from `add_regions`. If it helps, you could make the phantom say `@due(<time the expression evaluates to>)`, which is more explicit.

>How would you do it? while-loop? sublime.timeout or something?

Ideally, I'd put up a delayed `on_modified` hook that waits 500ms-1s after any key press to run. Additionally, an interval should be added for when you aren't modifying the view and not activating it either and I would use `sublime.set_timeout(_async)` for that. We don't need a thread for a simple task like this.

I would store (probably in a ViewEventListener) when we last updated a view. Whenever the callback is run, I would calculate the difference between now and the stored time + one minute. If that is >0, update now. If it is <0, call `sublime.set_timeout` again with the difference.

>  it would be better if PC shows version/tag so I don’t need to add it to message, and take note from matching filename in message folder instead of message.json.

I don't understand the first part, but agree on the second (https://github.com/wbond/package_control/issues/148).

> Besides, this package probably won’t introduce breaking changes so showing message is not that important, and there is rss for those who care about new features https://github.com/aziz/PlainTasks/commits/master.atom

Well, the phantom feature would have been a nice update announcement, but it is also discoverable enough that you notice it as soon as you open a file (and have `@due` tags in it). I do care about what features my packages add in updates, but I don't care about each commit and definitely cannot be bothered to hand-review all of them. Besides, package users could not understand Python in which case this helps them very little to not at all.

**Comment by vovkkk** [comment] 2016-12-13 00:20
> EventListeners should be removed from the event list when plugins are unloaded.

Do you mean they should be removed by ST automatically or should we add plugin_unloaded like this:

```python
def plugin_unloaded():
    for window in sublime.windows():
        for view in window.views():
            view.settings().clear_on_change('plain_tasks_remain_time_phantoms')
```

sublime is None seems related to reload/unload too.



> So, anyway, I encountered this today:
> 
> https://a.desu.sh/tynbem.mp4
> 
> Quite ... intersting I'd say.

Crazy. Never saw it. Dunno what else to say.

Speaking of places of phantoms and words, I’ve tried to explain you why they are as they are, the reasoning behind decisions, that doesn’t mean we cannot make them customisable.




> I'd put up a delayed on_modified hook that waits 500ms-1s after any key press to run

Wouldn’t it add annoying pauses when user types?



> I don't understand the first part

PC shows package name and messages, it would be nice if it showed name, version, message. I usually duplicate the latest message, rename it, change content; but sometimes forget to change [header which contains version](https://github.com/aziz/SublimeFileBrowser/commit/e9d81585552eefe8337b848e75e6a31616766a4a)



> I don't care about each commit and definitely cannot be bothered to hand-review all of them. Besides, package users could not understand Python in which case this helps them very little to not at all.

I understand what you mean, but in PT commit messages are mostly meaningful, so I’m just saying that in case of PT reading feed is just like reading changelog message, and non-trivial stuff is mostly documented in readme and tutorial so users don’t need to understand Python to see details of a change [usually].

**Comment by FichteFoll** [comment] 2016-12-13 10:24
>Do you mean they should be removed by ST automatically or should we add plugin_unloaded like this:

EventListeners are removed by ST but setting changed callbacks are not. Those need to be removed like you sampled in the post. I didn't realize you were using this (since I never looked at the code).

> Wouldn’t it add annoying pauses when user types?

It's how linter plugins work. Let the user perform changes until they pause with their typing and only peform a lint action during that. The delay is configurable, too.

**Closed** 2016-12-13 12:43 UTC
Labels: question
